provider "hcloud" {
  token = var.hcloud_token
}

# ─── Locals: Flatten nodes + auto IP ─────────────────────────────────
locals {
  manager_nodes = merge([
    for group_name, group in var.managers : {
      for i in range(group.replicas) :
      "${group_name}-${i}" => {
        group       = group_name
        server_type = group.server_type
        location    = group.location
        labels      = group.labels
        index       = i
      }
    }
  ]...)

  worker_nodes = merge([
    for group_name, group in var.workers : {
      for i in range(group.replicas) :
      "${group_name}-${i}" => {
        group       = group_name
        server_type = group.server_type
        location    = group.location
        labels      = group.labels
        index       = i
      }
    }
  ]...)

  all_node_keys     = concat(keys(local.manager_nodes), keys(local.worker_nodes))
  manager_node_keys = keys(local.manager_nodes)

  # Otomatik IP: offset'ten başlayarak sıralı
  node_ips = {
    for idx, key in local.all_node_keys :
    key => cidrhost(var.private_subnet, var.ip_offset + idx)
  }

  # İlk manager = Swarm leader
  leader_key = local.manager_node_keys[0]
  leader_ip  = local.node_ips[local.leader_key]

  # Phase 2 aktif mi?
  lockdown_enabled = var.netbird_setup_key != ""

  # SSH bağlantı ayarları — tekrar kullanım için
  ssh_key = file(pathexpand(var.ssh_private_key_path))

  # ─── CoreDNS hosts — otomatik oluşturulur ─────────────────────────
  coredns_hosts = join("\n", concat(
    ["# Auto-generated by Terraform — do not edit manually", ""],
    # Tüm manager'lar
    [for key, _ in local.manager_nodes :
      "${local.node_ips[key]} ${var.cluster_name}-mgr-${key}.internal mgr-${key}.internal"
    ],
    # Tüm worker'lar
    [for key, _ in local.worker_nodes :
      "${local.node_ips[key]} ${var.cluster_name}-wkr-${key}.internal wkr-${key}.internal"
    ],
    [""],
    ["# Service aliases (ilk node by role)"],
    # Grup kısa adları — her grubun ilk replica'sı
    [for key, node in local.worker_nodes :
      "${local.node_ips[key]} ${node.group}.internal"
      if node.index == 0
    ],
    # data grubundaki ilk node'a servis adları
    flatten([
      for key, node in local.worker_nodes : [
        "${local.node_ips[key]} pg.internal",
        "${local.node_ips[key]} redis.internal",
        "${local.node_ips[key]} minio.internal",
      ] if lookup(node.labels, "role", "") == "data" && node.index == 0
    ]),
  ))
}

# ─── SSH Key ──────────────────────────────────────────────────────────
resource "hcloud_ssh_key" "default" {
  name       = "${var.cluster_name}-key"
  public_key = file(pathexpand(var.ssh_public_key_path))
}

# ─── Private Network ─────────────────────────────────────────────────
resource "hcloud_network" "swarm" {
  name     = "${var.cluster_name}-network"
  ip_range = var.private_subnet
}

resource "hcloud_network_subnet" "swarm" {
  network_id   = hcloud_network.swarm.id
  type         = "cloud"
  network_zone = var.network_zone
  ip_range     = var.private_subnet
}

# ═════════════════════════════════════════════════════════════════════
# HETZNER FIREWALL
# netbird_setup_key boş  → Phase 1: Allow All (setup)
# netbird_setup_key dolu → Phase 2: Restricted (lockdown)
# ═════════════════════════════════════════════════════════════════════

resource "hcloud_firewall" "swarm" {
  name = "${var.cluster_name}-firewall"

  # ─── Phase 1: Allow All ────────────────────────────────────────────
  dynamic "rule" {
    for_each = local.lockdown_enabled ? [] : [1]
    content {
      direction  = "in"
      protocol   = "tcp"
      port       = "any"
      source_ips = ["0.0.0.0/0", "::/0"]
    }
  }

  dynamic "rule" {
    for_each = local.lockdown_enabled ? [] : [1]
    content {
      direction  = "in"
      protocol   = "udp"
      port       = "any"
      source_ips = ["0.0.0.0/0", "::/0"]
    }
  }

  # ─── Phase 2: Restricted Rules ────────────────────────────────────
  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "tcp"
      port        = "22"
      source_ips  = ["0.0.0.0/0", "::/0"]
      description = "SSH"
    }
  }

  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "tcp"
      port        = "80"
      source_ips  = ["0.0.0.0/0", "::/0"]
      description = "HTTP"
    }
  }

  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "tcp"
      port        = "443"
      source_ips  = ["0.0.0.0/0", "::/0"]
      description = "HTTPS"
    }
  }

  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "udp"
      port        = "51820"
      source_ips  = ["0.0.0.0/0", "::/0"]
      description = "WireGuard/NetBird"
    }
  }

  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "tcp"
      port        = "2377"
      source_ips  = [var.private_subnet]
      description = "Swarm management"
    }
  }

  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "tcp"
      port        = "7946"
      source_ips  = [var.private_subnet]
      description = "Swarm node TCP"
    }
  }

  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "udp"
      port        = "7946"
      source_ips  = [var.private_subnet]
      description = "Swarm node UDP"
    }
  }

  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "udp"
      port        = "4789"
      source_ips  = [var.private_subnet]
      description = "Overlay network"
    }
  }

  # ICMP — her zaman
  rule {
    direction  = "in"
    protocol   = "icmp"
    source_ips = ["0.0.0.0/0", "::/0"]
  }
}

# ─── Manager Nodes ───────────────────────────────────────────────────
module "manager_nodes" {
  source   = "./modules/swarm-node"
  for_each = local.manager_nodes

  name        = "${var.cluster_name}-mgr-${each.key}"
  server_type = each.value.server_type
  location    = each.value.location
  ssh_key_id  = hcloud_ssh_key.default.id
  network_id  = hcloud_network.swarm.id
  private_ip  = local.node_ips[each.key]
  subnet_id   = hcloud_network_subnet.swarm.id
  firewall_id = hcloud_firewall.swarm.id

  ssh_private_key_path = var.ssh_private_key_path
}

# ─── Worker Nodes ────────────────────────────────────────────────────
module "worker_nodes" {
  source   = "./modules/swarm-node"
  for_each = local.worker_nodes

  name        = "${var.cluster_name}-wkr-${each.key}"
  server_type = each.value.server_type
  location    = each.value.location
  ssh_key_id  = hcloud_ssh_key.default.id
  network_id  = hcloud_network.swarm.id
  private_ip  = local.node_ips[each.key]
  subnet_id   = hcloud_network_subnet.swarm.id
  firewall_id = hcloud_firewall.swarm.id

  ssh_private_key_path = var.ssh_private_key_path
}

# ═════════════════════════════════════════════════════════════════════
# SWARM ORCHESTRATION
# ═════════════════════════════════════════════════════════════════════

# ─── Step 1: Swarm Init ─────────────────────────────────────────────
resource "null_resource" "swarm_init" {
  depends_on = [module.manager_nodes]

  connection {
    type        = "ssh"
    host        = module.manager_nodes[local.leader_key].public_ip
    user        = "root"
    private_key = local.ssh_key
    timeout     = "5m"
  }

  provisioner "remote-exec" {
    inline = [
      "docker info --format '{{.Swarm.LocalNodeState}}' | grep -q 'active' || docker swarm init --advertise-addr ${local.leader_ip}",
      "docker network ls --format '{{.Name}}' | grep -q '^swarm_network$' || docker network create --driver overlay --attachable swarm_network",
    ]
  }
}

# ─── Step 2: Get Swarm Tokens ───────────────────────────────────────
data "external" "swarm_tokens" {
  depends_on = [null_resource.swarm_init]

  program = ["bash", "-c", <<-EOF
    SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -o ConnectTimeout=30"
    KEY="${pathexpand(var.ssh_private_key_path)}"
    HOST="${module.manager_nodes[local.leader_key].public_ip}"
    WORKER=$(ssh $SSH_OPTS -i "$KEY" root@"$HOST" "docker swarm join-token -q worker")
    MANAGER=$(ssh $SSH_OPTS -i "$KEY" root@"$HOST" "docker swarm join-token -q manager")
    echo "{\"worker\": \"$WORKER\", \"manager\": \"$MANAGER\"}"
  EOF
  ]
}

# ─── Step 3: Additional Managers Join ────────────────────────────────
resource "null_resource" "manager_join" {
  for_each = {
    for key, node in local.manager_nodes : key => node
    if key != local.leader_key
  }

  depends_on = [data.external.swarm_tokens]

  connection {
    type        = "ssh"
    host        = module.manager_nodes[each.key].public_ip
    user        = "root"
    private_key = local.ssh_key
    timeout     = "5m"
  }

  provisioner "remote-exec" {
    inline = [
      "docker info --format '{{.Swarm.LocalNodeState}}' | grep -q 'active' || docker swarm join --token ${data.external.swarm_tokens.result.manager} ${local.leader_ip}:2377",
    ]
  }
}

# ─── Step 4: Workers Join ───────────────────────────────────────────
resource "null_resource" "worker_join" {
  for_each = local.worker_nodes

  depends_on = [data.external.swarm_tokens]

  connection {
    type        = "ssh"
    host        = module.worker_nodes[each.key].public_ip
    user        = "root"
    private_key = local.ssh_key
    timeout     = "5m"
  }

  provisioner "remote-exec" {
    inline = [
      "docker info --format '{{.Swarm.LocalNodeState}}' | grep -q 'active' || docker swarm join --token ${data.external.swarm_tokens.result.worker} ${local.leader_ip}:2377",
    ]
  }
}

# ─── Step 5: Node Labels ────────────────────────────────────────────
resource "null_resource" "manager_labels" {
  for_each = {
    for key, node in local.manager_nodes : key => node
    if length(node.labels) > 0
  }

  depends_on = [null_resource.swarm_init, null_resource.manager_join]

  triggers = {
    labels = jsonencode(each.value.labels)
  }

  connection {
    type        = "ssh"
    host        = module.manager_nodes[local.leader_key].public_ip
    user        = "root"
    private_key = local.ssh_key
    timeout     = "5m"
  }

  provisioner "remote-exec" {
    inline = [
      for k, v in each.value.labels :
      "docker node update --label-add ${k}=${v} ${var.cluster_name}-mgr-${each.key}"
    ]
  }
}

resource "null_resource" "worker_labels" {
  for_each = {
    for key, node in local.worker_nodes : key => node
    if length(node.labels) > 0
  }

  depends_on = [null_resource.worker_join]

  triggers = {
    labels = jsonencode(each.value.labels)
  }

  connection {
    type        = "ssh"
    host        = module.manager_nodes[local.leader_key].public_ip
    user        = "root"
    private_key = local.ssh_key
    timeout     = "5m"
  }

  provisioner "remote-exec" {
    inline = [
      for k, v in each.value.labels :
      "docker node update --label-add ${k}=${v} ${var.cluster_name}-wkr-${each.key}"
    ]
  }
}

# ═════════════════════════════════════════════════════════════════════
# DOCKER SECRETS — CLI'da olan, Terraform'da eksik olan
# ═════════════════════════════════════════════════════════════════════

resource "null_resource" "docker_secrets" {
  depends_on = [null_resource.swarm_init]

  connection {
    type        = "ssh"
    host        = module.manager_nodes[local.leader_key].public_ip
    user        = "root"
    private_key = local.ssh_key
    timeout     = "5m"
  }

  provisioner "remote-exec" {
    inline = [
      <<-SCRIPT
      generate_secret() {
        openssl rand -base64 32 | tr -d '/+=' | head -c 32
      }

      create_secret_if_missing() {
        local name=$1
        if ! docker secret inspect "$name" >/dev/null 2>&1; then
          generate_secret | docker secret create "$name" -
          echo "  Created secret: $name"
        else
          echo "  Secret exists: $name"
        fi
      }

      echo "=== Creating Docker Secrets ==="
      create_secret_if_missing pg_password
      create_secret_if_missing pg_replication_password
      create_secret_if_missing redis_password
      create_secret_if_missing minio_root_password
      create_secret_if_missing registry_password
      echo "=== Secrets done ==="
      SCRIPT
    ]
  }
}

# ═════════════════════════════════════════════════════════════════════
# COREDNS AUTO-CONFIG
# ═════════════════════════════════════════════════════════════════════

resource "null_resource" "coredns_config" {
  depends_on = [module.manager_nodes, module.worker_nodes, null_resource.swarm_init]

  # Node eklenip çıkarıldığında hosts dosyasını güncelle
  triggers = {
    hosts_content = local.coredns_hosts
  }

  connection {
    type        = "ssh"
    host        = module.manager_nodes[local.leader_key].public_ip
    user        = "root"
    private_key = local.ssh_key
    timeout     = "5m"
  }

  provisioner "remote-exec" {
    inline = [
      "mkdir -p /opt/configs/coredns",
      "cat > /opt/configs/coredns/hosts.internal <<'HOSTS'\n${local.coredns_hosts}\nHOSTS",
    ]
  }
}

# ═════════════════════════════════════════════════════════════════════
# STACK DEPLOYMENT
# ═════════════════════════════════════════════════════════════════════

resource "null_resource" "deploy_stacks" {
  count = var.deploy_stacks ? 1 : 0

  depends_on = [
    null_resource.swarm_init,
    null_resource.manager_join,
    null_resource.worker_join,
    null_resource.manager_labels,
    null_resource.worker_labels,
    null_resource.coredns_config,
    null_resource.docker_secrets,
  ]

  connection {
    type        = "ssh"
    host        = module.manager_nodes[local.leader_key].public_ip
    user        = "root"
    private_key = local.ssh_key
    timeout     = "10m"
  }

  provisioner "file" {
    source      = "${path.module}/../stacks/"
    destination = "/opt/stacks"
  }

  provisioner "file" {
    source      = "${path.module}/../traefik/"
    destination = "/opt/traefik"
  }

  provisioner "remote-exec" {
    inline = [
      for stack in var.stacks :
      "echo 'Deploying ${stack.name}...' && docker stack deploy -c /opt/stacks/${stack.name}/docker-compose.yml ${stack.name} --with-registry-auth 2>&1 && echo '  OK: ${stack.name}' || echo '  WARN: ${stack.name} failed'"
    ]
  }
}

# ═════════════════════════════════════════════════════════════════════
# POST-DEPLOY — additional databases, registry login, backup cron
# ═════════════════════════════════════════════════════════════════════

resource "null_resource" "post_deploy" {
  count = var.deploy_stacks ? 1 : 0

  depends_on = [null_resource.deploy_stacks]

  connection {
    type        = "ssh"
    host        = module.manager_nodes[local.leader_key].public_ip
    user        = "root"
    private_key = local.ssh_key
    timeout     = "10m"
  }

  provisioner "remote-exec" {
    inline = [
      <<-SCRIPT
      echo "=== Waiting for PostgreSQL to be ready ==="
      for i in $(seq 1 30); do
        if docker exec $(docker ps -q -f name=data-postgresql) pg_isready -U postgres >/dev/null 2>&1; then
          echo "  PostgreSQL ready"
          break
        fi
        echo "  Waiting... ($i/30)"
        sleep 5
      done

      echo "=== Creating additional databases ==="
      PG_CONTAINER=$(docker ps -q -f name=data-postgresql)
      if [ -n "$PG_CONTAINER" ]; then
        docker exec "$PG_CONTAINER" psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'umami'" | grep -q 1 || \
          docker exec "$PG_CONTAINER" psql -U postgres -c "CREATE DATABASE umami;"
        docker exec "$PG_CONTAINER" psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'twenty'" | grep -q 1 || \
          docker exec "$PG_CONTAINER" psql -U postgres -c "CREATE DATABASE twenty;"
        echo "  Databases ready"
      else
        echo "  WARN: PostgreSQL container not found, skipping DB creation"
      fi

      echo "=== Setting up backup cron ==="
      BACKUP_SCRIPT="/opt/scripts/backup.sh"
      cat > "$BACKUP_SCRIPT" <<'BACKUP'
      #!/bin/bash
      set -euo pipefail
      BACKUP_DIR="/opt/backups/$(date +%Y-%m-%d)"
      mkdir -p "$BACKUP_DIR"

      # PostgreSQL
      PG=$(docker ps -q -f name=data-postgresql)
      if [ -n "$PG" ]; then
        docker exec "$PG" pg_dumpall -U postgres > "$BACKUP_DIR/pg_dumpall.sql" 2>/dev/null
        for db in $(docker exec "$PG" psql -U postgres -t -c "SELECT datname FROM pg_database WHERE datistemplate = false AND datname != 'postgres';" 2>/dev/null); do
          db=$(echo "$db" | xargs)
          [ -n "$db" ] && docker exec "$PG" pg_dump -U postgres -Fc "$db" > "$BACKUP_DIR/pg_${db}.dump" 2>/dev/null
        done
      fi

      # Redis
      REDIS=$(docker ps -q -f name=data-redis)
      if [ -n "$REDIS" ]; then
        docker exec "$REDIS" redis-cli BGSAVE >/dev/null 2>&1
        sleep 2
        docker cp "$REDIS":/data/dump.rdb "$BACKUP_DIR/redis.rdb" 2>/dev/null || true
      fi

      # Configs
      cp -r /opt/configs "$BACKUP_DIR/configs" 2>/dev/null || true
      cp -r /opt/traefik "$BACKUP_DIR/traefik" 2>/dev/null || true

      # Swarm state
      docker service ls --format '{{json .}}' > "$BACKUP_DIR/swarm-services.json" 2>/dev/null || true

      # Cleanup: 14 günden eski backup'ları sil
      find /opt/backups -maxdepth 1 -type d -mtime +14 -exec rm -rf {} \; 2>/dev/null || true

      echo "Backup completed: $BACKUP_DIR"
      BACKUP
      chmod +x "$BACKUP_SCRIPT"

      # Cron job ekle (yoksa)
      CRON_LINE="0 3 * * * $BACKUP_SCRIPT >> /var/log/backup.log 2>&1"
      (crontab -l 2>/dev/null | grep -qF "$BACKUP_SCRIPT") || \
        (crontab -l 2>/dev/null; echo "$CRON_LINE") | crontab -
      echo "  Backup cron installed (daily 03:00)"

      echo "=== Post-deploy complete ==="
      SCRIPT
    ]
  }
}

# ═════════════════════════════════════════════════════════════════════
# HEALTH CHECKS
# ═════════════════════════════════════════════════════════════════════

resource "null_resource" "health_checks" {
  count = var.deploy_stacks ? 1 : 0

  depends_on = [null_resource.post_deploy]

  connection {
    type        = "ssh"
    host        = module.manager_nodes[local.leader_key].public_ip
    user        = "root"
    private_key = local.ssh_key
    timeout     = "5m"
  }

  provisioner "remote-exec" {
    inline = [
      <<-SCRIPT
      echo "=== Health Checks ==="
      PASS=0; FAIL=0

      check() {
        local name=$1; local cmd=$2
        if eval "$cmd" >/dev/null 2>&1; then
          echo "  OK:   $name"
          PASS=$((PASS+1))
        else
          echo "  FAIL: $name"
          FAIL=$((FAIL+1))
        fi
      }

      # Swarm
      check "Swarm active" "docker info --format '{{.Swarm.LocalNodeState}}' | grep -q active"
      check "Network swarm_network" "docker network ls --format '{{.Name}}' | grep -q swarm_network"

      # Services
      check "PostgreSQL" "docker exec \$(docker ps -q -f name=data-postgresql 2>/dev/null) pg_isready -U postgres 2>/dev/null"
      check "Redis" "docker exec \$(docker ps -q -f name=data-redis 2>/dev/null) redis-cli ping 2>/dev/null | grep -q PONG"
      check "Traefik" "curl -sf http://localhost:8080/api/overview >/dev/null 2>&1 || docker service ls --format '{{.Name}} {{.Replicas}}' | grep traefik | grep -q '1/1'"
      check "CoreDNS" "docker service ls --format '{{.Name}} {{.Replicas}}' | grep dns | grep -q '1/1'"

      echo ""
      echo "Results: $PASS passed, $FAIL failed"
      [ "$FAIL" -eq 0 ] || echo "WARNING: Some health checks failed"
      SCRIPT
    ]
  }
}

# ═════════════════════════════════════════════════════════════════════
# PHASE 2: LOCKDOWN — netbird_setup_key verildiğinde aktif olur
# ═════════════════════════════════════════════════════════════════════

resource "null_resource" "lockdown_managers" {
  for_each = local.lockdown_enabled ? local.manager_nodes : {}

  depends_on = [null_resource.deploy_stacks, null_resource.swarm_init]

  connection {
    type        = "ssh"
    host        = module.manager_nodes[each.key].public_ip
    user        = "root"
    private_key = local.ssh_key
    timeout     = "5m"
  }

  provisioner "remote-exec" {
    inline = [
      "echo '=== Phase 2: Lockdown on ${var.cluster_name}-mgr-${each.key} ==='",
      "command -v netbird >/dev/null || curl -fsSL https://pkgs.netbird.io/install.sh | sh",
      "netbird status 2>/dev/null | grep -q 'Connected' || netbird up --setup-key '${var.netbird_setup_key}'",
      "netbird status",
      "ufw status | grep -q 'Status: active' || /opt/scripts/enable-ufw.sh",
      "echo 'Lockdown complete on ${var.cluster_name}-mgr-${each.key}'",
    ]
  }
}

resource "null_resource" "lockdown_workers" {
  for_each = local.lockdown_enabled ? local.worker_nodes : {}

  depends_on = [null_resource.deploy_stacks, null_resource.worker_join]

  connection {
    type        = "ssh"
    host        = module.worker_nodes[each.key].public_ip
    user        = "root"
    private_key = local.ssh_key
    timeout     = "5m"
  }

  provisioner "remote-exec" {
    inline = [
      "echo '=== Phase 2: Lockdown on ${var.cluster_name}-wkr-${each.key} ==='",
      "command -v netbird >/dev/null || curl -fsSL https://pkgs.netbird.io/install.sh | sh",
      "netbird status 2>/dev/null | grep -q 'Connected' || netbird up --setup-key '${var.netbird_setup_key}'",
      "netbird status",
      "ufw status | grep -q 'Status: active' || /opt/scripts/enable-ufw.sh",
      "echo 'Lockdown complete on ${var.cluster_name}-wkr-${each.key}'",
    ]
  }
}
