provider "hcloud" {
  token = var.hcloud_token
}

# ─── Locals: Flatten nodes + auto IP ─────────────────────────────────
locals {
  manager_nodes = merge([
    for group_name, group in var.managers : {
      for i in range(group.replicas) :
      "${group_name}-${i}" => {
        group       = group_name
        server_type = group.server_type
        location    = group.location
        labels      = group.labels
        index       = i
      }
    }
  ]...)

  worker_nodes = merge([
    for group_name, group in var.workers : {
      for i in range(group.replicas) :
      "${group_name}-${i}" => {
        group       = group_name
        server_type = group.server_type
        location    = group.location
        labels      = group.labels
        index       = i
      }
    }
  ]...)

  all_node_keys     = concat(keys(local.manager_nodes), keys(local.worker_nodes))
  manager_node_keys = keys(local.manager_nodes)

  # Otomatik IP: offset'ten başlayarak sıralı
  node_ips = {
    for idx, key in local.all_node_keys :
    key => cidrhost(var.private_subnet, var.ip_offset + idx)
  }

  # İlk manager = Swarm leader
  leader_key = local.manager_node_keys[0]
  leader_ip  = local.node_ips[local.leader_key]

  # Phase 2 aktif mi?
  lockdown_enabled = var.netbird_setup_key != ""

  # ─── CoreDNS hosts — otomatik oluşturulur ─────────────────────────
  coredns_hosts = join("\n", concat(
    ["# Auto-generated by Terraform — do not edit manually", ""],
    # Tüm manager'lar
    [for key, _ in local.manager_nodes :
      "${local.node_ips[key]} ${var.cluster_name}-mgr-${key}.internal mgr-${key}.internal"
    ],
    # Tüm worker'lar
    [for key, _ in local.worker_nodes :
      "${local.node_ips[key]} ${var.cluster_name}-wkr-${key}.internal wkr-${key}.internal"
    ],
    [""],
    ["# Service aliases (ilk node by role)"],
    # Grup kısa adları — her grubun ilk replica'sı
    [for key, node in local.worker_nodes :
      "${local.node_ips[key]} ${node.group}.internal"
      if node.index == 0
    ],
    # data grubundaki ilk node'a servis adları
    flatten([
      for key, node in local.worker_nodes : [
        "${local.node_ips[key]} pg.internal",
        "${local.node_ips[key]} redis.internal",
        "${local.node_ips[key]} minio.internal",
      ] if lookup(node.labels, "role", "") == "data" && node.index == 0
    ]),
  ))
}

# ─── SSH Key ──────────────────────────────────────────────────────────
resource "hcloud_ssh_key" "default" {
  name       = "${var.cluster_name}-key"
  public_key = file(pathexpand(var.ssh_public_key_path))
}

# ─── Private Network ─────────────────────────────────────────────────
resource "hcloud_network" "swarm" {
  name     = "${var.cluster_name}-network"
  ip_range = var.private_subnet
}

resource "hcloud_network_subnet" "swarm" {
  network_id   = hcloud_network.swarm.id
  type         = "cloud"
  network_zone = var.network_zone
  ip_range     = var.private_subnet
}

# ═════════════════════════════════════════════════════════════════════
# HETZNER FIREWALL
# netbird_setup_key boş  → Phase 1: Allow All (setup)
# netbird_setup_key dolu → Phase 2: Restricted (lockdown)
# ═════════════════════════════════════════════════════════════════════

resource "hcloud_firewall" "swarm" {
  name = "${var.cluster_name}-firewall"

  # ─── Phase 1: Allow All ────────────────────────────────────────────
  dynamic "rule" {
    for_each = local.lockdown_enabled ? [] : [1]
    content {
      direction  = "in"
      protocol   = "tcp"
      port       = "any"
      source_ips = ["0.0.0.0/0", "::/0"]
    }
  }

  dynamic "rule" {
    for_each = local.lockdown_enabled ? [] : [1]
    content {
      direction  = "in"
      protocol   = "udp"
      port       = "any"
      source_ips = ["0.0.0.0/0", "::/0"]
    }
  }

  # ─── Phase 2: Restricted Rules ────────────────────────────────────
  # SSH
  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "tcp"
      port        = "22"
      source_ips  = ["0.0.0.0/0", "::/0"]
      description = "SSH"
    }
  }

  # HTTP
  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "tcp"
      port        = "80"
      source_ips  = ["0.0.0.0/0", "::/0"]
      description = "HTTP"
    }
  }

  # HTTPS
  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "tcp"
      port        = "443"
      source_ips  = ["0.0.0.0/0", "::/0"]
      description = "HTTPS"
    }
  }

  # WireGuard (NetBird)
  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "udp"
      port        = "51820"
      source_ips  = ["0.0.0.0/0", "::/0"]
      description = "WireGuard/NetBird"
    }
  }

  # Swarm management — sadece private subnet
  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "tcp"
      port        = "2377"
      source_ips  = [var.private_subnet]
      description = "Swarm management"
    }
  }

  # Swarm node communication
  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "tcp"
      port        = "7946"
      source_ips  = [var.private_subnet]
      description = "Swarm node TCP"
    }
  }

  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "udp"
      port        = "7946"
      source_ips  = [var.private_subnet]
      description = "Swarm node UDP"
    }
  }

  # Overlay network
  dynamic "rule" {
    for_each = local.lockdown_enabled ? [1] : []
    content {
      direction   = "in"
      protocol    = "udp"
      port        = "4789"
      source_ips  = [var.private_subnet]
      description = "Overlay network"
    }
  }

  # ICMP — her zaman
  rule {
    direction  = "in"
    protocol   = "icmp"
    source_ips = ["0.0.0.0/0", "::/0"]
  }
}

# ─── Manager Nodes ───────────────────────────────────────────────────
module "manager_nodes" {
  source   = "./modules/swarm-node"
  for_each = local.manager_nodes

  name        = "${var.cluster_name}-mgr-${each.key}"
  server_type = each.value.server_type
  location    = each.value.location
  ssh_key_id  = hcloud_ssh_key.default.id
  network_id  = hcloud_network.swarm.id
  private_ip  = local.node_ips[each.key]
  subnet_id   = hcloud_network_subnet.swarm.id
  firewall_id = hcloud_firewall.swarm.id

  ssh_private_key_path = var.ssh_private_key_path
}

# ─── Worker Nodes ────────────────────────────────────────────────────
module "worker_nodes" {
  source   = "./modules/swarm-node"
  for_each = local.worker_nodes

  name        = "${var.cluster_name}-wkr-${each.key}"
  server_type = each.value.server_type
  location    = each.value.location
  ssh_key_id  = hcloud_ssh_key.default.id
  network_id  = hcloud_network.swarm.id
  private_ip  = local.node_ips[each.key]
  subnet_id   = hcloud_network_subnet.swarm.id
  firewall_id = hcloud_firewall.swarm.id

  ssh_private_key_path = var.ssh_private_key_path
}

# ═════════════════════════════════════════════════════════════════════
# SWARM ORCHESTRATION
# ═════════════════════════════════════════════════════════════════════

resource "null_resource" "swarm_init" {
  depends_on = [module.manager_nodes]

  connection {
    type        = "ssh"
    host        = module.manager_nodes[local.leader_key].public_ip
    user        = "root"
    private_key = file(pathexpand(var.ssh_private_key_path))
    timeout     = "5m"
  }

  provisioner "remote-exec" {
    inline = [
      "docker swarm init --advertise-addr ${local.leader_ip} 2>/dev/null || echo 'Swarm already initialized'",
      "docker network create --driver overlay --attachable swarm_network 2>/dev/null || echo 'Network swarm_network already exists'",
    ]
  }
}

data "external" "swarm_tokens" {
  depends_on = [null_resource.swarm_init]

  program = ["bash", "-c", <<-EOF
    SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"
    KEY="${pathexpand(var.ssh_private_key_path)}"
    HOST="${module.manager_nodes[local.leader_key].public_ip}"
    WORKER=$(ssh $SSH_OPTS -i "$KEY" root@"$HOST" "docker swarm join-token -q worker")
    MANAGER=$(ssh $SSH_OPTS -i "$KEY" root@"$HOST" "docker swarm join-token -q manager")
    echo "{\"worker\": \"$WORKER\", \"manager\": \"$MANAGER\"}"
  EOF
  ]
}

resource "null_resource" "manager_join" {
  for_each = {
    for key, node in local.manager_nodes : key => node
    if key != local.leader_key
  }

  depends_on = [data.external.swarm_tokens]

  connection {
    type        = "ssh"
    host        = module.manager_nodes[each.key].public_ip
    user        = "root"
    private_key = file(pathexpand(var.ssh_private_key_path))
  }

  provisioner "remote-exec" {
    inline = [
      "docker swarm join --token ${data.external.swarm_tokens.result.manager} ${local.leader_ip}:2377 2>/dev/null || echo 'Already in swarm'",
    ]
  }
}

resource "null_resource" "worker_join" {
  for_each = local.worker_nodes

  depends_on = [data.external.swarm_tokens]

  connection {
    type        = "ssh"
    host        = module.worker_nodes[each.key].public_ip
    user        = "root"
    private_key = file(pathexpand(var.ssh_private_key_path))
  }

  provisioner "remote-exec" {
    inline = [
      "docker swarm join --token ${data.external.swarm_tokens.result.worker} ${local.leader_ip}:2377 2>/dev/null || echo 'Already in swarm'",
    ]
  }
}

resource "null_resource" "manager_labels" {
  for_each = {
    for key, node in local.manager_nodes : key => node
    if length(node.labels) > 0
  }

  depends_on = [null_resource.swarm_init, null_resource.manager_join]

  connection {
    type        = "ssh"
    host        = module.manager_nodes[local.leader_key].public_ip
    user        = "root"
    private_key = file(pathexpand(var.ssh_private_key_path))
  }

  provisioner "remote-exec" {
    inline = [
      for k, v in each.value.labels :
      "docker node update --label-add ${k}=${v} ${var.cluster_name}-mgr-${each.key}"
    ]
  }
}

resource "null_resource" "worker_labels" {
  for_each = {
    for key, node in local.worker_nodes : key => node
    if length(node.labels) > 0
  }

  depends_on = [null_resource.worker_join]

  connection {
    type        = "ssh"
    host        = module.manager_nodes[local.leader_key].public_ip
    user        = "root"
    private_key = file(pathexpand(var.ssh_private_key_path))
  }

  provisioner "remote-exec" {
    inline = [
      for k, v in each.value.labels :
      "docker node update --label-add ${k}=${v} ${var.cluster_name}-wkr-${each.key}"
    ]
  }
}

# ═════════════════════════════════════════════════════════════════════
# COREDNS AUTO-CONFIG
# ═════════════════════════════════════════════════════════════════════

resource "null_resource" "coredns_config" {
  depends_on = [null_resource.swarm_init]

  # Node eklenip çıkarıldığında hosts dosyasını güncelle
  triggers = {
    hosts_content = local.coredns_hosts
  }

  connection {
    type        = "ssh"
    host        = module.manager_nodes[local.leader_key].public_ip
    user        = "root"
    private_key = file(pathexpand(var.ssh_private_key_path))
  }

  provisioner "remote-exec" {
    inline = [
      "mkdir -p /opt/configs/coredns",
      "cat > /opt/configs/coredns/hosts.internal <<'HOSTS'\n${local.coredns_hosts}\nHOSTS",
    ]
  }
}

# ═════════════════════════════════════════════════════════════════════
# STACK DEPLOYMENT
# ═════════════════════════════════════════════════════════════════════

resource "null_resource" "deploy_stacks" {
  count = var.deploy_stacks ? 1 : 0

  depends_on = [
    null_resource.swarm_init,
    null_resource.manager_join,
    null_resource.worker_join,
    null_resource.manager_labels,
    null_resource.worker_labels,
    null_resource.coredns_config,
  ]

  connection {
    type        = "ssh"
    host        = module.manager_nodes[local.leader_key].public_ip
    user        = "root"
    private_key = file(pathexpand(var.ssh_private_key_path))
  }

  provisioner "file" {
    source      = "${path.module}/../stacks/"
    destination = "/opt/stacks"
  }

  provisioner "file" {
    source      = "${path.module}/../traefik/"
    destination = "/opt/traefik"
  }

  provisioner "remote-exec" {
    inline = [
      for stack in var.stacks :
      "echo 'Deploying ${stack.name}...' && docker stack deploy -c /opt/stacks/${stack.name}/docker-compose.yml ${stack.name} --with-registry-auth 2>&1 && echo '  OK: ${stack.name}' || echo '  WARN: ${stack.name} failed'"
    ]
  }
}

# ═════════════════════════════════════════════════════════════════════
# PHASE 2: LOCKDOWN — netbird_setup_key verildiğinde aktif olur
# NetBird kurulur, UFW açılır, Hetzner FW kısıtlanır
# ═════════════════════════════════════════════════════════════════════

# ─── NetBird Install + UFW Enable on Managers ────────────────────────
resource "null_resource" "lockdown_managers" {
  for_each = local.lockdown_enabled ? local.manager_nodes : {}

  depends_on = [null_resource.deploy_stacks, null_resource.swarm_init]

  connection {
    type        = "ssh"
    host        = module.manager_nodes[each.key].public_ip
    user        = "root"
    private_key = file(pathexpand(var.ssh_private_key_path))
  }

  provisioner "remote-exec" {
    inline = [
      "echo '=== Phase 2: Lockdown on ${var.cluster_name}-mgr-${each.key} ==='",
      "command -v netbird >/dev/null || curl -fsSL https://pkgs.netbird.io/install.sh | sh",
      "netbird status | grep -q 'Connected' || netbird up --setup-key '${var.netbird_setup_key}'",
      "netbird status",
      "ufw status | grep -q 'Status: active' || /opt/scripts/enable-ufw.sh",
      "echo 'Lockdown complete on ${var.cluster_name}-mgr-${each.key}'",
    ]
  }
}

# ─── NetBird Install + UFW Enable on Workers ────────────────────────
resource "null_resource" "lockdown_workers" {
  for_each = local.lockdown_enabled ? local.worker_nodes : {}

  depends_on = [null_resource.deploy_stacks, null_resource.worker_join]

  connection {
    type        = "ssh"
    host        = module.worker_nodes[each.key].public_ip
    user        = "root"
    private_key = file(pathexpand(var.ssh_private_key_path))
  }

  provisioner "remote-exec" {
    inline = [
      "echo '=== Phase 2: Lockdown on ${var.cluster_name}-wkr-${each.key} ==='",
      "command -v netbird >/dev/null || curl -fsSL https://pkgs.netbird.io/install.sh | sh",
      "netbird status | grep -q 'Connected' || netbird up --setup-key '${var.netbird_setup_key}'",
      "netbird status",
      "ufw status | grep -q 'Status: active' || /opt/scripts/enable-ufw.sh",
      "echo 'Lockdown complete on ${var.cluster_name}-wkr-${each.key}'",
    ]
  }
}
