version: "3.8"

services:
  promtail:
    image: grafana/promtail:3.3.0
    command: ["-config.file=/etc/promtail/promtail-config.yml"]
    volumes:
      - /opt/configs/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - swarm_network
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 60s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  swarm_network:
    external: true
